---
title: "SImulation Results"
author: "Bianca Brusco"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,cache=TRUE)
source(here::here("src/print_sim20230713_results.R"))
```


Population Size = 400 stations
True values:
SIGMA2X = 3
BETA1 = 2

## SIMULATION FOR PHI-X = 0.2

```{r}
PHIX <- 0.2
```

### Sample Size: 120

```{r,echo=FALSE}
SAMPLE_SIZE <- 120
print_results()
```

### Sample Size: 200

```{r,echo=FALSE}
SAMPLE_SIZE <- 200
print_results()
```

### Sample Size: 280

```{r,echo=FALSE}
SAMPLE_SIZE <- 280
print_results()
```

## SIMULATION FOR PHI-X = 0.5

```{r}
PHIX <- 0.5
```

### Sample Size: 120

```{r,echo=FALSE}
SAMPLE_SIZE <- 120
print_results()
```

### Sample Size: 200

```{r,echo=FALSE}
SAMPLE_SIZE <- 200
print_results()
```

### Sample Size: 280

```{r,echo=FALSE}
SAMPLE_SIZE <- 280
print_results()
```


## SIMULATION FOR PHI-X = 1

```{r}
PHIX <- 0.5
```

### Sample Size: 120

```{r,echo=FALSE}
SAMPLE_SIZE <- 120
print_results()
```

### Sample Size: 200

```{r,echo=FALSE}
SAMPLE_SIZE <- 200
print_results()
```

### Sample Size: 280

```{r,echo=FALSE}
SAMPLE_SIZE <- 280
print_results()
```




## SIMULATION FOR PHI-X = 1

```{r}
PHIX <- 1
```

### Sample Size: 120

```{r,echo=FALSE}
SAMPLE_SIZE <- 120
print_results()
```

### Sample Size: 200

```{r,echo=FALSE}
SAMPLE_SIZE <- 200
print_results()
```

### Sample Size: 280

```{r,echo=FALSE}
SAMPLE_SIZE <- 280
print_results()
```
